name: Run Solutions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-javascript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Run Code
        run: node . run
      - name: Validate Code
        run: node . validate
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: data.json
